# Generated by Django 3.2.2 on 2022-10-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRsystem', '0004_alter_complaint_type_of_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='lost_found',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lost_item', models.CharField(max_length=100)),
                ('item_description', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
